services:
  db:
    image: mysql
    container_name: bitcoingold_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - bitcoingold_data:/var/lib/mysql

volumes:
  bitcoingold_data: